apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: slack-crsx-discussions
spec:
  template:
    spec:
      containers:
        - image: ko://knativecon/demo1/cmd/slack-sink
          env:
            - name: SLACK_CHANNEL_ID
              value: C03DU6G596Z
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-secret
                  key: token
